### ISSUE TITLE
Not working on `.sheet` modal view. 

### ISSUE THREAD

**Issue by addel** [neel-makhecha/AlertX#2]
Hello,

Your component seems to not working on `.sheet` modifier. Could you confirm please ? 

Thank you.

**Comment by neel-makhecha** [comment]
Hi, will you please elaborate the issue? 
If you are referring to something where you try to change the @State property that's being used to present sheet from any button action in AlertX, then it may not seem to work because of a small bug that's in there. So it would be great if you can elaborate the issue. Thanks!

**Comment by addel** [comment]
Hi,
I've tried this and it seem to not working.
I want that your Alert work also on a `.sheet` modifier.

```swift
import SwiftUI
import AlertX

struct ContentView: View {
    @State var isSheetPresented: Bool = false
    @State var showAlertX: Bool = false
    
    var body: some View {
        Button(action: { isSheetPresented = true }, label: {
            Text("Button")
        })
        .sheet(isPresented: $isSheetPresented) {
            Button(action: {
                    self.showAlertX = true
                }, label: {
                    Text("Show AlertX")
                })
            .alertX(isPresented: $showAlertX, content: {
                    AlertX(title: Text("The Title"), theme: .wine())
            })
        }
    }
}
```

Thank you ;-)

**Comment by jsunnb** [comment]
I am also having the same problem, after I do .sheet(isPresented:....) and then trying to show an AlertX from that presented view nothing happens. I'm wondering if the AlertX view is presenting behind the .sheet(isPresented:....) view?

**Comment by neel-makhecha** [comment]
Hi @jsunnb, this issue is already resolved. Please make sure you are on the latest version of AlertX. If you still find any issue, please feel free to reach out. 
Thanks!

**Comment by jsunnb** [comment]
Awesome! I just took a look and saw that the View Extension file was about 5 days old. I updated that file and everything seems to work as I would expect it to. Thank you so much for responding! You did a really great job with this library!

Jason
