### ISSUE TITLE
Button actions freeze the UI

### ISSUE THREAD

**Issue by mdescalzo** [neel-makhecha/AlertX#3]
I'm attempting to use AlertX to display a delete validation alert, but when I include anything in a button actions that modifies properties, the alert dismisses and then dims the entire view and won't allow further touches to the app.  It is as if there is an invisible alert that I can't interact with.  This renders the app unusable.  Put nothing in the action or print() to console works as expected.

Here is the code I'm using.  I have a custom theme I built, but the above isn't dependent upon theme.

```
AlertX(title: Text("Please Confirm"),
                                      message: Text("Do you want to remove this contact?"),
                                      primaryButton: .default(Text("Delete"), action: {
                                        contacts.remove(atOffsets: deleteIndexSet!)
                                        deleteIndexSet = nil
                                      }),
                                      secondaryButton: .cancel(Text("Cancel"), action:{
                                        deleteIndexSet = nil
                                      }))
```

**Comment by neel-makhecha** [comment]
Hi Mark,

Thanks for the issue. It is now resolved in the release 1.1.1. 

Check out this commit: https://github.com/neel-makhecha/AlertX/commit/44ed7688066954762b72345844310899365c031c

Let me know if there're any other issues.
