### ISSUE TITLE
Under what License are you distributing AlertX?

### ISSUE THREAD

**Issue by aikow** [neel-makhecha/AlertX#6]
Hello, I'm currently working on an MIT open source project and was wondering what the exact license of this project is.
Since no license is supplied, it follows that the project is currently under the default license, meaning I currently can't use this project. 

Could you perhaps please add a license to remedy this?

Kind regards

**Comment by neel-makhecha** [comment]
Hello, this project is now licensed under MIT License. Please feel free to use AlertX in your projects. 
Thanks!
