### ISSUE TITLE
Rounded corner radius

### ISSUE THREAD

**Issue by antonjazz** [neel-makhecha/AlertX#9]
Thank you for this wonderful package! Such a great improvement on the SwiftUI **alert** class!
Have you given any thought to allowing customization of additional parameters? In particular, the corner radius of 25 for rounded corners is unusually large — about double what's customary in iOS design. And yet unrounded corners are also unusual in iOS UI. I'd love to be able to round corners using a medium radius.

thanks again!

**Comment by neel-makhecha** [comment]
Hi @antonjazz, thanks for this issue and drawing the attention towards that. Thanks to a PR submitted by @rcobelli, you can now change the corner radius parameter.

**Comment by antonjazz** [comment]
Fantastic - thank you, @rcobelli!
And thanks again, @neel-makhecha.
